// Re-export from shared protocol package so server imports remain unchanged.
export {
  LocalAgenticToolName,
  KNOWN_LOCAL_AGENTIC_TOOLS,
  LocalAgenticToolCall,
  LocalAgenticFinal,
  LocalAgenticAction,
  LOCAL_AGENTIC_PROTOCOL_INSTRUCTIONS,
  LOCAL_AGENTIC_DEFAULTS,
  LOCAL_AGENTIC_DELEGATION_TOOLS,
  parseLocalAgenticAction,
  buildLocalAgenticTurnPrompt,
  compactJson,
  promptRequestsDelegation,
  runAgenticLoop,
  runChatAgenticLoop,
  getOllamaToolSchemas,
  buildOllamaSystemMessage,
  // MCP tool adapters
  mcpToolsToOllamaSchemas,
  mcpResultToLoopResult,
  mcpToolsToTextPrompt,
} from "@arkestrator/protocol";
export type {
  ParsedLocalAgenticAction,
  LocalAgenticHistoryEntry,
  AgenticLoopConfig,
  AgenticLoopDeps,
  AgenticLoopResult,
  AgenticLoopLlmResponse,
  AgenticLoopToolResult,
  AgenticLoopCommandRecord,
  AgenticLoopChatResponse,
  OllamaChatMessage,
  OllamaToolSchema,
  OllamaToolCall,
  // MCP adapter types
  McpToolDefinition,
  McpToolCallResult,
} from "@arkestrator/protocol";
